---
dist: xenial
language: python
python: 3.7
services: docker
env:
  global:
    - IMAGE_NAME=dhsncats/example
    - DOCKER_USER=felddy
    # DOCKER_PW
    - secure: "ENoShlh71u2RhvoBgT5tx/d7TowkoCvCrlaQ5lL7vRelcb4+p8m7UPvKhu1t\
      6adyqsW0EJxMS3fZgZQUx8f2Yv4CsJVET5r8weYf/9p2+/g2wPm0RuteDqS2dl75gpLII\
      HBomaR9Kx10eZsiIPZGrusqt0B5OaLsWkKrmcLIknjsaavK8wkzrPho6q47cNhsClFqpN\
      3kkduUev0E7l5h9nyKLtWNONCKq9o+7xMBTuUfxYBXcRgfcfnwCgW2+R9F8umNqExcTVK\
      u1a7ueF6jPMEGCuj3tLjGIpjd32NG3IuLB+dfpQ7IeRBw5V+6y/+BP71msBhLzdr/1VY9\
      QVp+LDl4x1U9yxKo5esb3Rs0v0Ss9tKab6wbG9q8DhY9LeU6gXTcUA4oNN0/jw/iESWA5\
      cgtXtuE9mmXSnYmTY9gxG3UJtZiwkbHEt9+l91TMDCBNI3hBHaeyotIFdZk+QkpnchURV\
      M7rgnN81CHoK8FptufuzLzwMYNGvfYhQNOn4zLMv6Uch/8J028zVi/U2XHNelrLyQKoOa\
      M0sgU8nS0Fw+sp1dlHnFREgPDm57YxbnBUhKU4oF5ClAtJlQHeH11KWZUQkWMEOnkNT2S\
      1HMaI7MFcqCFAhxjFoHMszG+F7CgcSdOltqRwtJi1z8FVnNs4fxK4Ysv0UcEaYmfccM55\
      a8="
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
install:
  - pip install --upgrade --requirement requirements-test.txt
  - version=$(./bump_version.sh show)
  - docker build
    --tag "$IMAGE_NAME"
    --build-arg GIT_COMMIT=$(git log -1 --format=%H)
    --build-arg GIT_REMOTE=$(git remote get-url origin)
    --build-arg VERSION=${version}
    .
script:
  - pre-commit run --all-files
  - pytest --verbose
before_deploy:
  - IFS='.' read -r -a version_array <<< "$version"
  - docker login --username "$DOCKER_USER" --password "$DOCKER_PW"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
  - docker tag "$IMAGE_NAME"
    "${IMAGE_NAME}:${version_array[0]}.${version_array[1]}"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version_array[0]}"
deploy:
  - provider: script
    script: docker push "${IMAGE_NAME}:latest" &&
      docker push "${IMAGE_NAME}:${version}" &&
      docker push "${IMAGE_NAME}:${version_array[0]}.${version_array[1]}" &&
      docker push "${IMAGE_NAME}:${version_array[0]}" &&
      ./push_readme.sh
    on:
      tags: true
      python: '3.7'
