---
version: "3.7"

# This docker-compose file is used to build and test the container

secrets:
  credentials:
    file: ./src/secrets/credentials

services:
  certboto:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    image: cisagov/certboto
    init: true
    restart: "no"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - BUCKET_NAME=cool-test-certs
      - BUCKET_PROFILE=bucket-role
      - DNS_PROFILE=dns-role
    secrets:
      - source: credentials
        target: credentials

  certboto-version:
    # Run the container to collect version information
    image: cisagov/certboto
    init: true
    restart: "no"
    command: --version
